app:
    resource: "@AppBundle/Controller/"
    type:     annotation
homepage:
   path: /{page}
   defaults: { _controller: AppBundle:Guest:homepage, page: 1 }
create:
   path: /create
   defaults: { _controller: AppBundle:Guest:create }   
delete:
   path: /delete/{id}
   defaults: { _controller: AppBundle:Guest:delete }  
login:
  path: /admin
  defaults: { _controller: AppBundle:Admin:admin }